import { useState, useEffect } from "react";
import { motion, AnimatePresence } from "framer-motion";
import BlogCard from "./BlogCard";
import { BookOpen, X, Terminal, FileText, Tag } from "lucide-react";
import blogsData from "../data/blogs";

export default function Blogs() {
  const [selected, setSelected] = useState(null);

  const defaultBlogs = [
    {
      title: "Phishing Detector Analysis",
      tag: "Cyber Security | Threat Detection",
      category: "Threat Detection",
      date: "2026",
      description: "Technical writeup on building a defensive rule-based phishing detection system for identifying malicious URLs.",
      content: `
Phishing attacks are one of the most common cybersecurity threats where attackers create fake websites or messages to steal sensitive information.

I built a rule-based phishing detector to identify suspicious URLs using security checks and predefined detection rules.

WHY IT IS NEEDED:
Phishing attacks target users, organizations and companies. A detection system helps identify malicious links before users interact with them.

USE CASES:
• Detect suspicious URLs and malicious domain structures
• Improve security awareness and automated link screening
• Assist SOC analysts in identifying incoming phishing threats

CHALLENGES:
While building the project, challenges included creating accurate detection rules and reducing false positive results.

SOLUTION:
I improved the detection logic by adding multiple security validation checks and analyzing URL behavior patterns.
      `,
    },
    {
      title: "Building My Wazuh Home Lab",
      tag: "SIEM | SOC Operations",
      category: "SOC Operations",
      date: "2026",
      description: "Step-by-step documentation on setting up a personal SIEM environment using Wazuh for log monitoring and security alerts.",
      content: `
A Wazuh Home Lab is a personal security monitoring environment used to understand how Security Operations Centers work in practice.

PURPOSE:
The lab helps in learning log monitoring, alert generation, endpoint visibility, and threat detection.

IMPLEMENTATION:
Configured Wazuh SIEM environment across Linux agent nodes and analyzed real-time security events generated by endpoints.

CHALLENGES:
Understanding security logs, correlation rules, and configuring monitoring rules was challenging.

LEARNING:
The project significantly improved my practical knowledge about SOC operations, defensive security, and incident analysis.
      `,
    },
    {
      title: "Building My Cybersecurity Portfolio",
      tag: "Development | UI/UX",
      category: "Security Interface",
      date: "2026",
      description: "Design philosophy and architectural decisions behind building a modern security engineer digital identity.",
      content: `
This portfolio is designed as a cybersecurity command interface instead of a normal developer website.

TECHNOLOGY USED:
• React + Vite
• Tailwind CSS
• Framer Motion

FEATURES:
• Interactive Security Console
• SOC Operations Panel
• Project Case Files
• Certification Showcase

GOAL:
Create a unique, security-focused portfolio representing my cybersecurity journey and technical capabilities.
      `,
    },
  ];

  const blogsList = blogsData && blogsData.length > 0 ? blogsData : defaultBlogs;

  useEffect(() => {
    const handleKeyDown = (e) => {
      if (e.key === "Escape") setSelected(null);
    };
    window.addEventListener("keydown", handleKeyDown);
    return () => window.removeEventListener("keydown", handleKeyDown);
  }, []);

  return (
    <section id="blogs" className="w-full max-w-7xl mx-auto px-4 sm:px-6 lg:px-12 py-24 relative">
      {/* Background Glow */}
      <div className="absolute top-1/3 left-10 w-72 h-72 bg-emerald-500/5 rounded-full blur-[100px] pointer-events-none" />

      {/* SECTION HEADER */}
      <div className="flex flex-col items-start mb-14">
        <div className="inline-flex items-center gap-2 px-3 py-1 rounded-full bg-emerald-500/10 border border-emerald-500/20 text-emerald-400 font-mono text-xs tracking-wider mb-3">
          <Terminal className="w-3.5 h-3.5" />
          <span>TECHNICAL WRITEUPS</span>
        </div>
        <h2 className="text-3xl sm:text-4xl font-bold text-white font-sans tracking-tight">
          SECURITY <span className="text-emerald-400">REPORTS</span>
        </h2>
        <p className="mt-2 text-slate-400 text-sm sm:text-base max-w-2xl">
          Detailed technical writeups, security research, lab documentations, and engineering reports.
        </p>
      </div>

      {/* BLOGS GRID */}
      <div className="grid grid-cols-1 md:grid-cols-2 lg:grid-cols-3 gap-8 items-stretch">
        {blogsList.map((blog, index) => (
          <div key={index} className="h-full">
            <BlogCard blog={blog} onClick={() => setSelected(blog)} />
          </div>
        ))}
      </div>

      {/* READ REPORT MODAL */}
      <AnimatePresence>
        {selected && (
          <div
            onClick={() => setSelected(null)}
            className="fixed inset-0 z-50 bg-black/80 backdrop-blur-md flex items-center justify-center p-4 sm:p-6 overflow-y-auto"
          >
            <motion.div
              initial={{ opacity: 0, scale: 0.95, y: 20 }}
              animate={{ opacity: 1, scale: 1, y: 0 }}
              exit={{ opacity: 0, scale: 0.95, y: 20 }}
              transition={{ duration: 0.25, ease: "easeOut" }}
              onClick={(e) => e.stopPropagation()}
              className="w-full max-w-3xl rounded-2xl bg-[#080e0c] border border-emerald-500/30 p-6 sm:p-8 shadow-[0_25px_60px_rgba(0,0,0,0.9)] max-h-[90vh] overflow-y-auto relative"
            >
              {/* CLOSE BUTTON */}
              <button
                onClick={() => setSelected(null)}
                className="absolute top-6 right-6 p-2 rounded-xl bg-white/5 border border-white/10 text-slate-400 hover:text-white hover:bg-white/10 transition-colors cursor-pointer"
                aria-label="Close report modal"
              >
                <X className="w-5 h-5" />
              </button>

              {/* MODAL HEADER */}
              <div className="flex items-center gap-2 mb-3">
                <span className="text-xs font-mono text-emerald-400 font-medium tracking-wide uppercase px-2.5 py-1 rounded bg-emerald-500/10 border border-emerald-500/25 flex items-center gap-1">
                  <Tag className="w-3 h-3" />
                  {selected.tag || selected.category || "SECURITY WRITEUP"}
                </span>
                <span className="text-xs font-mono text-slate-400">
                  {selected.date || "2026"}
                </span>
              </div>

              <h2 className="text-2xl sm:text-3xl font-bold text-white font-sans pr-10">
                {selected.title}
              </h2>

              {/* CONTENT BODY */}
              <div className="mt-6 pt-6 border-t border-emerald-500/15 text-slate-300 text-sm leading-relaxed whitespace-pre-line font-sans bg-[#040706] p-5 rounded-xl border border-emerald-500/15">
                {selected.content}
              </div>

              {/* MODAL FOOTER */}
              <div className="mt-8 pt-4 border-t border-emerald-500/20 flex items-center justify-between">
                <span className="text-xs font-mono text-emerald-400/80">
                  REPORT ID: SEC-{Math.floor(1000 + Math.random() * 9000)}
                </span>
                <button
                  onClick={() => setSelected(null)}
                  className="px-5 py-2.5 rounded-xl bg-emerald-500/10 hover:bg-emerald-500/20 text-emerald-400 border border-emerald-500/30 text-xs font-mono tracking-wide transition-colors cursor-pointer"
                >
                  CLOSE REPORT
                </button>
              </div>
            </motion.div>
          </div>
        )}
      </AnimatePresence>
    </section>
  );
}