import {useState} from "react";
import {motion} from "framer-motion";


const blogs=[


{

title:"Phishing Detector",

tag:"Cyber Security",

content:

`

Phishing attacks are one of the most common cybersecurity threats where attackers create fake websites or messages to steal sensitive information.

I built a rule based phishing detector to identify suspicious URLs using security checks and predefined detection rules.


Why it is needed:

Phishing attacks target users, organizations and companies. A detection system helps identify malicious links before users interact with them.


Use Cases:

• Detect suspicious URLs

• Improve security awareness

• Assist users in identifying threats


Challenges:

While building the project, challenges included creating accurate detection rules and reducing false positives.


Solution:

I improved the detection logic by adding multiple security checks and analyzing URL behaviour patterns.

`

},






{

title:"Wazuh Home Lab",

tag:"SIEM",

content:

`

A Wazuh Home Lab is a personal security monitoring environment used to understand how Security Operations Centers work.


Purpose:

The lab helps in learning log monitoring, alert generation and threat detection.


Implementation:

Configured Wazuh SIEM environment and studied security events generated by endpoints.


Challenges:

Understanding security logs and configuring monitoring rules was challenging.


Learning:

The project improved my knowledge about SOC operations and defensive security.

`

},






{

title:"Cybersecurity Portfolio",

tag:"Development",

content:

`

This portfolio is designed as a cybersecurity command interface instead of a normal website.


Technology Used:

• React

• Tailwind CSS

• Framer Motion


Features:

• Interactive terminal

• Security dashboard

• Project case files

• Certification showcase


Goal:

Create a unique security focused portfolio representing my cybersecurity journey.

`

}



];






export default function Blogs(){



const [selected,setSelected]=useState(null);





return(


<section

id="blogs"

className="

px-5

sm:px-8

py-20

max-w-7xl

mx-auto

"

>



<h2

className="

text-3xl

sm:text-4xl

text-green-400

font-mono

mb-10

"

>

&gt; SECURITY_REPORTS_

</h2>








<div

className="

grid

grid-cols-1

md:grid-cols-2

lg:grid-cols-3

gap-8

"

>





{

blogs.map((blog,index)=>(



<motion.div


key={index}



whileHover={{

scale:1.05,

rotateY:8

}}



onClick={()=>setSelected(blog)}



className="

bg-black

border

border-green-500/40

rounded-xl

p-6

cursor-pointer

shadow-[0_0_40px_rgba(0,255,100,.2)]

"

>




<p

className="

text-green-400

text-sm

font-mono

"

>

{blog.tag}

</p>






<h3

className="

text-white

text-2xl

font-bold

mt-4

"

>

{blog.title}

</h3>







<p

className="

text-gray-400

mt-5

"

>

Click to open report...

</p>







<div

className="

text-green-400

mt-6

font-mono

"

>

&gt; OPEN_REPORT_

</div>






</motion.div>


))


}





</div>













{

selected &&



<div

className="

fixed

inset-0

bg-black/90

z-50

flex

items-center

justify-center

p-5

"

>



<div

className="

bg-black

border

border-green-500

rounded-xl

max-w-3xl

max-h-[80vh]

overflow-y-auto

p-8

shadow-[0_0_80px_rgba(0,255,100,.3)]

"

>



<h2

className="

text-3xl

text-green-400

font-bold

"

>

{selected.title}

</h2>




<div

className="

mt-6

text-gray-300

whitespace-pre-line

leading-7

"

>

{selected.content}

</div>






<button


onClick={()=>setSelected(null)}



className="

mt-8

border

border-green-500

px-5

py-2

text-green-400

hover:bg-green-500

hover:text-black

"

>

CLOSE_REPORT

</button>




</div>



</div>



}





</section>


)

}